---
repo: AdobeDocs/commerce.en
url: https://experienceleague.adobe.com/en/docs/commerce/user-guides/home
exclude:
  - Rakefile
  - tmp
  - rakelib
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
